---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # 设置存储大小
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home-assistant
  template:
    metadata:
      labels:
        app: home-assistant
    spec:
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:stable
          securityContext:
            privileged: true
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8123
              name: http
          env:
            - name: TZ
              value: Asia/Shanghai
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-config
        - name: localtime
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  ports:
    - port: 8123
      targetPort: http
      protocol: TCP
  selector:
    app: home-assistant
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-backup
  labels:
    app: home-assistant
spec:
  ports:
    - port: 8123
      targetPort: http
      nodePort: 30001
  selector:
    app: home-assistant
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  rules:
  - host: ha.homelab.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: home-assistant
            port:
              number: 8123
