---
apiVersion: v1
kind: Secret
metadata:
  name: admin
type: Opaque
stringData:
  # 设置前请修改 `账号`+`密码`
  # shell `kubectl apply -f administrator.yaml`
  username: username # required field for kubernetes.io/basic-auth
  password: password # required field for kubernetes.io/basic-auth
