---
apiVersion: v1
kind: Service
metadata:
  name: notebook
  labels:
    app: notebook
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 8888
    nodePort: 30002
  selector:
    app: notebook
---
apiVersion: v1
kind: Pod
metadata:
  name: notebook
  labels:
    app: notebook
spec:
  securityContext:
    fsGroup: 0
  containers:
  - name: notebook
    # image: tensorflow/tensorflow:latest-gpu-jupyter
    image: quay.io/jupyter/pytorch-notebook:cuda11-pytorch-2.2.1
    resources:
      requests:
        nvidia.com/gpu: 1
      limits:
        nvidia.com/gpu: 1
    ports:
    - containerPort: 8888
      name: notebook
