---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piwigo-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piwigo
  labels:
    app: piwigo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piwigo
  template:
    metadata:
      labels:
        app: piwigo
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node1
      containers:
        - name: piwigo
          image: lscr.io/linuxserver/piwigo:14.2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 4000m
              memory: 8Gi
          volumeMounts:
            - mountPath: /gallery
              name: gallery
            - mountPath: /config
              name: config
      volumes:
        - name: gallery
          nfs:
            path: /Multimedia/Media/Gallery
            server: quts.homelab.com
        - name: config
          persistentVolumeClaim:
            claimName: piwigo-config
---
apiVersion: v1
kind: Service
metadata:
  name: piwigo-backup
  labels:
    app: piwigo
spec:
  ports:
    - port: 80
      targetPort: http
      nodePort: 30001
  selector:
    app: piwigo
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: piwigo
  labels:
    app: piwigo
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: piwigo
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: piwigo
  labels:
    app: piwigo
spec:
  rules:
  - host: piwigo.homelab.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: piwigo
            port:
              number: 80
