version: '3'

volumes:
  grafana: {}

services:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    ports:
      - '3000:3000'
    volumes:
      - grafana:/var/lib/grafana
