image:
  repository: m.daocloud.io/registry.k8s.io/sig-storage/nfs-subdir-external-provisioner  # 使用国内镜像源
  tag: v4.0.2
  pullPolicy: IfNotPresent

nfs:
  # 配置你的NFS共享目录
  server: quts.homelab.com
  path: /Kubernetes/rke2
# # 默认不使用挂载选项
# mountOptions:
#   - nfsvers=4.2

storageClass:
  defaultClass: true
  name: standard
  allowVolumeExpansion: true
  provisionerName: nfs-subdir-external-provisioner

nodeSelector:
  kubernetes.io/hostname: server
