image:
# repository: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
# repository: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner # 已过期
  repository: liukunup/nfs-subdir-external-provisioner
  tag: v4.0.2
  pullPolicy: IfNotPresent

nfs:
  # 配置你的NFS共享目录
  server: quts.homelab.com
  path: /Kubernetes/rke2
# mountOptions:
#   - nfsvers=4.2

storageClass:
  defaultClass: true
  name: standard
  allowVolumeExpansion: true
  provisionerName: nfs-subdir-external-provisioner

nodeSelector:
  kubernetes.io/hostname: server
