storageClass:
  name: standard
  defaultClass: true
  allowVolumeExpansion: true
  provisionerName: k8s-sigs.io/nfs-subdir-external-provisioner
nfs:
  server: quts.homelab.com
  path: /Kubernetes/pve
  mountOptions:
    - nfsvers=4.2
