storageClass:
  name: nas-qnap-kubernetes
  defaultClass: true
  allowVolumeExpansion: true
  provisionerName: k8s-sigs.io/nfs-subdir-external-provisioner
nfs:
  server: qnap.liukun.com
  path: /Kubernetes  # +/c4m16 or +/c48m64g1
  mountOptions:
    - nfsvers=4.2
