version: "3"

networks:
  notebook:
    driver: bridge

volumes:
  notebook-python:
  notebook-cpp:
  notebook-sql:

services:

  # Python
  notebook-python:
    image: jupyter/minimal-notebook:notebook-6.5.2
    container_name: notebook-python
    hostname: notebook-python
    command: start-notebook.sh --NotebookApp.password=${JUPYTER_NOTEBOOK_PASSWORD:?error}
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
      - DOCKER_STACKS_JUPYTER_CMD=lab
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    volumes:
      - notebook-python:/home/jovyan/work
    ports:
      - "8888:8888"
    networks:
      - notebook

  # C++
  notebook-cpp:
    image: datainpoint/xeus-cling-notebook:latest
    container_name: notebook-cpp
    hostname: notebook-cpp
    command: start-notebook.sh --NotebookApp.password=${JUPYTER_NOTEBOOK_PASSWORD:?error}
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
      - DOCKER_STACKS_JUPYTER_CMD=lab
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    volumes:
      - notebook-cpp:/home/jovyan/work
    ports:
      - "8889:8888"
    networks:
      - notebook

  # SQL
  notebook-sql:
    image: datainpoint/xeus-sql-notebook:latest
    container_name: notebook-sql
    hostname: notebook-sql
    command: start-notebook.sh --NotebookApp.password=${JUPYTER_NOTEBOOK_PASSWORD:?error}
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
      - DOCKER_STACKS_JUPYTER_CMD=lab
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    volumes:
      - notebook-sql:/home/jovyan/work
    ports:
      - "8890:8888"
    networks:
      - notebook
