#cloud-config

chpasswd:
  expire: false
  users:
  - {name: root, password: $6$8EUkAsCo3tFHpXpU$5qD47Ycp4eqTVL/fcMgsLqKW9plxBl3hZvPIC1bmDNyDWI83zZKWTeedPPoNRqo.AZlmbR2kYJUtxFOCmIuqg1}
ssh_pwauth: true

timezone: Asia/Shanghai
hostname: debian

users:
  - name: liukunup
    gecos: LiuKun
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCVfqsj2EzWrJ49sArn3yJ1B2Lm0zEKcVLEU9+PxReULdDiXlyvcdncPqYOdkL8izH5qOHJwnuCAmtKkQvA+rh9G9v+ns7MASOTW6K75bRrBiXx/h4tRZ9G94IlbohRRn7bvoqiCJEypPUqnJcFVASZNBN2vxRT11pyDtsKhB7yAcS74x2DjcSirO7sI02JNJNxmWZERGlibtbRh4Wuwldwxh2z+RHkA4uuE/IzZXlymKO4h27n+dV+z4nppCgzf+L3aC5EPmYC18e0xWBG4VOr2KNaBgCzwquJ8Ymwzc9xghx8sM37NT3uYE5W//CJMLWo2DhsqJhEpi3376N7zodlK6Zt7SjEx2kaPuUZEB9UMGgPw1hSd+JJJTuccJMIe1gUrtNgnr3qnRHTDUZEPMsfp6SvmgFFqmJTfdvE/DctsYEtqdjfaLq8dm4mjE/aFkZVElfmhNQ7Gx/nd2p4vN9ccu7W6JehQ1HFgS8eYWJJ6NjkcI2y6ftlZwC/4kxWYc8= liukunup@163.com
    passwd: $6$8EUkAsCo3tFHpXpU$5qD47Ycp4eqTVL/fcMgsLqKW9plxBl3hZvPIC1bmDNyDWI83zZKWTeedPPoNRqo.AZlmbR2kYJUtxFOCmIuqg1
    lock_passwd: false

apt:
  primary:
    - arches: [default]
      uri: https://mirrors.ustc.edu.cn/debian
  security:
    - arches: [default]
      uri: https://mirrors.ustc.edu.cn/debian-security

package_reboot_if_required: true
package_update: true
package_upgrade: true

packages:
  - qemu-guest-agent
  - vim
  - curl
  - wget
  - git
  - nfs-common
  - net-tools
  - software-properties-common
  - ca-certificates

runcmd:
  # 安装 docker
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
  - usermod -aG docker liukunup
  - ln -s /usr/libexec/docker/cli-plugins/docker-buildx /usr/bin/docker-buildx
  - ln -s /usr/libexec/docker/cli-plugins/docker-compose /usr/bin/docker-compose
  # 安装 nvidia 12.8.1
  - wget https://developer.download.nvidia.com/compute/cuda/12.8.1/local_installers/cuda-repo-debian12-12-8-local_12.8.1-570.124.06-1_amd64.deb
  - dpkg -i cuda-repo-debian12-12-8-local_12.8.1-570.124.06-1_amd64.deb
  - cp /var/cuda-repo-debian12-12-8-local/cuda-*-keyring.gpg /usr/share/keyrings/
  - apt-get update
  - apt-get install cuda-toolkit-12-8 -y
  - apt-get install cuda-drivers -y
  # 安装 nvidia-docker
  - distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
    && curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - \
    && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
  - apt-get update
  - apt-get install nvidia-docker2 -y
  - systemctl restart docker
  # 清理
  - apt autoremove -y
  - apt clean
  # 收尾工作
  - systemctl enable docker
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent