networks:
    1panel-network:
        external: true

services:
    act_runner:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        environment:
            - CONFIG_FILE=/config.yaml
            - GITEA_INSTANCE_URL=${GITEA_INSTANCE_URL}
            - GITEA_RUNNER_REGISTRATION_TOKEN=${RUNNER_REGISTRATION_TOKEN}
            - GITEA_RUNNER_NAME=${RUNNER_NAME}
        image: gitea/act_runner:latest
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        restart: unless-stopped
        volumes:
            - ./config.yaml:/config.yaml
            - ./runner:/data
            - /var/run/docker.sock:/var/run/docker.sock
