version: "3"

volumes:
  syncthing-config:
  syncthing-data:

services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    restart: unless-stopped
    ports:
      - "8384:8384"       # Web GUI
      - "22000:22000/tcp" # Sync TCP
      - "22000:22000/udp" # Sync UDP
      - "21027:21027/udp" # Discovery
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
    volumes:
      - syncthing-config:/var/syncthing
      - syncthing-data:/var/syncthing/data
