version: "3"

# 生产环境请确保数据可靠存储
volumes:
  syncthing-discosrv-data:
  syncthing-relaysrv-data:

services:

  syncthing-discosrv:
    image: syncthing/discosrv:latest
    container_name: syncthing-discovery-server
    hostname: discosrv
    restart: unless-stopped
    command: -listen=":8443"
    ports:
      - "8443:8443"
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
    volumes:
      - syncthing-discosrv-data:/var/stdiscosrv

  syncthing-relaysrv:
    image: syncthing/relaysrv:latest
    container_name: syncthing-relay-server
    hostname: relaysrv
    restart: unless-stopped
    command: -listen=":22067" -pools=""
    ports:
      - "22067:22067"
      - "22070:22070" 
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
    volumes:
      - syncthing-relaysrv-data:/var/strelaysrv
