# docs: https://version-2025-8.goauthentik.io/install-config/install/docker-compose
# reference: https://goauthentik.io/docker-compose.yml

networks:
  1panel-network:
    external: true

services:
  server:
    command: server
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: ${PG_HOST:-postgresql}
      AUTHENTIK_POSTGRESQL__PORT: ${PG_PORT:-5432}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_REDIS__HOST: ${REDIS_HOST:-redis}
      AUTHENTIK_REDIS__PORT: ${REDIS_PORT:-6379}
      AUTHENTIK_REDIS__PASSWORD: ${REDIS_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.8.1}
    ports:
    - ${AUTHENTIK_PORT_HTTP:-9000}:9000
    - ${AUTHENTIK_PORT_HTTPS:-9443}:9443
    restart: unless-stopped
    volumes:
    - ./media:/media
    - ./custom-templates:/templates
    networks:
    - 1panel-network
  worker:
    command: worker
    env_file:
    - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: ${PG_HOST:-postgresql}
      AUTHENTIK_POSTGRESQL__PORT: ${PG_PORT:-5432}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_REDIS__HOST: ${REDIS_HOST:-redis}
      AUTHENTIK_REDIS__PORT: ${REDIS_PORT:-6379}
      AUTHENTIK_REDIS__PASSWORD: ${REDIS_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.8.1}
    restart: unless-stopped
    user: root
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./media:/media
    - ./certs:/certs
    - ./custom-templates:/templates
    networks:
    - 1panel-network