authentik:
  secret_key: "JXSAZH5X7SNXHDnVsNM+t3EBgc/MzS2NDPsSSju67OErtVO9"
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.io, and is fully opt-in
  error_reporting:
    enabled: true
  disable_update_check: true
  disable_startup_analytics: true
  postgresql:
    password: "gRqfnS57WjW39oMT"
  email:
    host: "smtp.163.com"
    port: 587
    username: "liukunbot@163.com"
    password: "changme"
    use_tls: true
    use_ssl: false
    timeout: 30
    from: "LiuKun <liukunbot@163.com>"

server:
  ingress:
    ingressClassName: nginx
    enabled: true
    hosts:
      - authentik.homelab.com

postgresql:
  enabled: true
  auth:
    password: "gRqfnS57WjW39oMT"

redis:
    enabled: true
