version: "3"

volumes:
  config:

services:

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    hostname: code-server
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - PUID=1000
      - PGID=1000
      - PASSWORD=${MY_PASSWORD:?error}
      - SUDO_PASSWORD=${MY_PASSWORD:?error}
      - PROXY_DOMAIN=${NAS_DOMAIN:?error}
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - config:/config
    ports:
      - "8443:8443"
    network_mode: host
