---
apiVersion: v1
kind: Secret
metadata:
  name: minio
type: Opaque
stringData:
  # 设置前请修改 `账号`+`密码`
  # shell `kubectl apply -f password.yaml`
  root-user: username # required field for kubernetes.io/basic-auth
  root-password: password # required field for kubernetes.io/basic-auth