---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
stringData:
  # 设置前请修改 `账号`+`密码`
  # shell `kubectl apply -f password.yaml`
  mysql-root-password: "wZ6try8MCNGi6n8P" # required field for kubernetes.io/basic-auth
  mysql-replication-password: "FnVYR8Hno&kHp3sN" # required field for kubernetes.io/basic-auth
  mysql-password: "password" # required field for kubernetes.io/basic-auth
