---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
stringData:
  # 设置前请修改 `账号`+`密码`
  # shell `kubectl apply -f password.yaml`
  mysql-root-password: password # required field for kubernetes.io/basic-auth
  mysql-replication-password: password # required field for kubernetes.io/basic-auth
  mysql-password: password # required field for kubernetes.io/basic-auth
