# 设置身份验证参数
auth:
  # 设置 `root` 超级管理员密码
  rootPassword: "123456"
  # 创建自定义数据库(以电商为例)
  database: "e_commerce"
  username: "e_commerce"
  password: "123456"

# 主从复制(一主二从)
architecture: replication
# 主数据库
primary:
  persistence:
    size: 8Gi
# 从数据库
secondary:
  replicaCount: 2
  persistence:
    size: 8Gi

# 使能`Network Policy`并允许任意外部来源的访问
networkPolicy:
  enabled: true
  allowExternal: true
