# Dev Stack

networks:
  dev-stack:
    name: ${NETWORK_NAME}
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  minio-data:
  etcd-data:
  kafka-data:
  zookeeper-data:
  apisix-data:
  code-server-config:
  notebook-python-data:
  notebook-cpp-data:
  notebook-sql-data:
  nginx-data:
  grafana-data:

services:

  # MySQL
  mysql:
    image: ${REGISTRY:-docker.io}/${MYSQL_IMAGE:-mysql:latest}
    container_name: mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?root password is required}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-testing}
      MYSQL_USER: ${MYSQL_USER:-testing}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?password is required}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dev-stack
    profiles:
      - all
      - base
      - database
      - mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis
  redis:
    image: ${REGISTRY:-docker.io}/${REDIS_IMAGE:-redis:latest}
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:?password is required}
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - redis-data:/data
    networks:
      - dev-stack
    profiles:
      - all
      - base
      - cache
      - redis
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MinIO
  minio:
    image: ${REGISTRY:-docker.io}/${MINIO_IMAGE:-minio/minio:latest}
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    ports:
      - ${MINIO_API_PORT:-9000}:9000
      - ${MINIO_CONSOLE_PORT:-9001}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USERNAME:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?password is required}
    volumes:
      - minio-data:/data
    networks:
      - dev-stack
    profiles:
      - all
      - base
      - storage
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  # etcd
  etcd:
    image: ${REGISTRY_QUAY:-quay.io}/${ETCD_IMAGE:-coreos/etcd:latest}
    container_name: etcd
    restart: unless-stopped
    command:
      - /usr/local/bin/etcd
      - --data-dir /etcd-data
      - --name etcd-single-node
      - --initial-advertise-peer-urls http://etcd:2380
      - --listen-client-urls http://0.0.0.0:2379
      - --listen-peer-urls http://0.0.0.0:2380
      - --advertise-client-urls http://etcd:2379
      - --initial-cluster etcd-single-node=http://etcd:2380
    ports:
      - ${ETCD_CLIENT_PORT:-2379}:2379
      - ${ETCD_PEER_PORT:-2380}:2380
    volumes:
      - etcd-data:/etcd-data
    networks:
      - dev-stack
    profiles:
      - all
      - kv # key-value store
      - etcd
      - apisix # etcd is used by APISIX
    healthcheck:
      test: ["CMD", "curl", "-k", "http://localhost:2379/livez"]
      interval: 30s
      timeout: 10s
      retries: 3

  # ZooKeeper
  zookeeper:
    image: ${REGISTRY:-docker.io}/${ZOOKEEPER_IMAGE:-zookeeper:3.9.4}
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - ${ZOOKEEPER_PORT:-2181}:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/data
    networks:
      - dev-stack
    profiles:
      - all
      - mq
      - zookeeper

  # Kafka
  kafka:
    image: ${REGISTRY:-docker.io}/${KAFKA_IMAGE:-kafka:3.9.1}
    container_name: kafka
    restart: unless-stopped
    ports:
      - ${KAFKA_PORT:-9092}:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - dev-stack
    profiles:
      - all
      - mq
      - kafka

  # apisix
  apisix:
    image: ${REGISTRY:-docker.io}/${APISIX_IMAGE:-apache/apisix:3.13.0-debian}
    container_name: apisix
    restart: unless-stopped
    ports:
      - ${APISIX_HTTP_PORT:-9080}:9080     # HTTP
      - ${APISIX_HTTPS_PORT:-9443}:9443    # HTTPS
      - ${APISIX_CONTROL_PORT:-9090}:9090  # Control Plane
      - ${APISIX_METRICS_PORT:-9091}:9091  # Prometheus metrics
      - ${APISIX_ADMIN_PORT:-9180}:9180    # Admin API
    environment:
      APISIX_API_KEY: ${APISIX_API_KEY:?api key is required}
      APISIX_DEPLOYMENT_ETCD_HOST: etcd
      APISIX_DEPLOYMENT_ETCD_PORT: 2379
      APISIX_DEPLOYMENT_ETCD_USER: ${ETCD_ROOT_USERNAME:-admin}
      APISIX_DEPLOYMENT_ETCD_PASSWORD: ${ETCD_ROOT_PASSWORD:?root password is required}
    volumes:
      - apisix-data:/usr/local/apisix
    depends_on:
      - etcd
    networks:
      - dev-stack
    profiles:
      - all
      - api-gateway
      - gateway
      - apisix

  # code-server
  # https://github.com/coder/code-server
  # Run VS Code on any machine anywhere and access it in the browser.
  code-server:
    image: ${REGISTRY:-docker.io}/${CODE_SERVER_IMAGE:-codercom/code-server:latest}
    container_name: code-server
    restart: unless-stopped
    ports:
      - ${HOST_IP:-127.0.0.1}:${CODE_SERVER_PORT:-8080}:8080
    volumes:
      - code-server-config:/home/coder/.config
      # Optional
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dev-stack
    profiles:
      - all
      - ide
      - code-server
      - vscode

  # Jupyter Notebook - Python
  notebook-python:
    image: ${REGISTRY_QUAY:-quay.io}/${NOTEBOOK_PYTHON_IMAGE:-jupyter/minimal-notebook:latest}
    container_name: notebook-python
    hostname: notebook-python
    command: start-notebook.sh --NotebookApp.password=${NOTEBOOK_PYTHON_PASSWORD:?password is required}
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      LANG: ${LANG:-en_US.UTF-8}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      DOCKER_STACKS_JUPYTER_CMD: lab
      JUPYTER_ENABLE_LAB: yes
      GRANT_SUDO: yes
    volumes:
      - notebook-python-data:/home/jovyan/work
    ports:
      - ${NOTEBOOK_PYTHON_PORT:-8888}:8888
    networks:
      - dev-stack
    profiles:
      - all
      - notebook
      - python
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/lab"]
      interval: 30s
      timeout: 10s
      retries: 3

  # C++
  notebook-cpp:
    image: ${REGISTRY:-docker.io}/${NOTEBOOK_CPP_IMAGE:-datainpoint/xeus-cling-notebook:latest}
    container_name: notebook-cpp
    hostname: notebook-cpp
    command: start-notebook.sh --NotebookApp.password=${NOTEBOOK_CPP_PASSWORD:?password is required}
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      LANG: ${LANG:-en_US.UTF-8}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      DOCKER_STACKS_JUPYTER_CMD: lab
      JUPYTER_ENABLE_LAB: yes
      GRANT_SUDO: yes
    volumes:
      - notebook-cpp-data:/home/jovyan/work
    ports:
      - ${NOTEBOOK_CPP_PORT:-8889}:8888
    networks:
      - dev-stack
    profiles:
      - all
      - notebook
      - cpp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/lab"]
      interval: 30s
      timeout: 10s
      retries: 3

  # SQL
  notebook-sql:
    image: ${REGISTRY:-docker.io}/${NOTEBOOK_SQL_IMAGE:-datainpoint/xeus-sql-notebook:latest}
    container_name: notebook-sql
    hostname: notebook-sql
    command: start-notebook.sh --NotebookApp.password=${NOTEBOOK_SQL_PASSWORD:?password is required}
    restart: unless-stopped
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      LANG: ${LANG:-en_US.UTF-8}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      DOCKER_STACKS_JUPYTER_CMD: lab
      JUPYTER_ENABLE_LAB: yes
      GRANT_SUDO: yes
    volumes:
      - notebook-sql-data:/home/jovyan/work
    ports:
      - ${NOTEBOOK_SQL_PORT:-8890}:8888
    networks:
      - dev-stack
    profiles:
      - all
      - notebook
      - sql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/lab"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx
  nginx:
    image: ${REGISTRY:-docker.io}/${NGINX_IMAGE:-nginx:latest}
    container_name: nginx
    restart: unless-stopped
    ports:
      - ${NGINX_HTTP_PORT:-80}:80
      - ${NGINX_HTTPS_PORT:-443}:443
    volumes:
      - nginx-data:/etc/nginx
    networks:
      - dev-stack
    profiles:
      - all
      - web
      - nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Grafana
  grafana:
    image: ${REGISTRY:-docker.io}/${GRAFANA_IMAGE:-grafana/grafana:latest}
    container_name: grafana
    restart: unless-stopped
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-changeit}
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - dev-stack
    profiles:
      - all
      - monitoring
      - grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/robots.txt"]
      interval: 30s
      timeout: 10s
      retries: 3
