---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: k8s-sigs.io/nfs-subdir-external-provisioner
spec:
  storageClassName: nas-qnap-kubernetes  # 请确保`StorageClass`已存在
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
