apiVersion: v1
kind: Secret
metadata:
  name: centralized-minio-users
type: Opaque
stringData:
  adminstrator: |
    username=admin
    password=Harbor12345
    disabled=false
    policies=readwrite,consoleAdmin,diagnostics
    setPolicies=false
