---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook
  labels:
    app: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
        - name: notebook
          image: jupyter/minimal-notebook:notebook-6.5.2
          imagePullPolicy: IfNotPresent
          command: ["start-notebook.sh"]
          args:
            - --NotebookApp.password='sha1:a7c0702d28e9:8a8868c5d4ea33af70e04c634487402b3997f40c'
          ports:
            - containerPort: 8888
              name: http
              protocol: TCP
          env:
            - name: DOCKER_STACKS_JUPYTER_CMD
              value: 'lab'
            - name: GRANT_SUDO
              value: 'yes'
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 4000m
              memory: 8Gi
              nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: /home/jovyan/work
              name: work
      volumes:
        - name: work
          persistentVolumeClaim:
            claimName: notebook
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
